services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d