spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joybox
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


cloud:
  aws:
    endpoint: http://127.0.0.1:4566
    accessKey: access-key
    secretKey: secret-key
    region: region
    bucket: image

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /api-docs
