openapi: 3.0.1
info:
  version: 1.0.0
  title: Product API
  description: Apis to get and manage products
paths:
  /api/{id}:
    get:
      tags:
        - Product
      operationId: getProduct
      description: Get product details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  /api/{image}:
    post:
      tags:
        - ProductImage
      operationId: addImage
      description: Add Image details
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddImageResponse"

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - price
        - description
      properties:
        id:
          type: integer
          description: id of product
          example: 12
        title:
          type: string
          description: title of product
          example: Elden Ring
        price:
          type: integer
          description: price of product
          example: 64000
        description:
          type: string
          description: description for product
          example: This game is awesome!!
    AddImageResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: id
          example: "550e8400-e29b-41d4-a716-446655440000"
          